services:
  - type: web
    name: knut-obfuscator
    runtime: node
    repo: https://github.com/knut-sigm/KNUT-OBFUS.git
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MAX_FILE_SIZE
        value: 104857600
    autoDeploy: true
    domains:
      - knut-obfuscator.onrender.com
